-- V1 基线：Public Beta 完整 schema（16 张表 + 索引 + 岗位方向字典种子）。
-- 由旧仓库的 V1–V7 演化链在开源 1.0 基线时合并而成，演化历史随旧仓库退役；
-- 数据模型语义见 docs/database/database-design.md。

-- ================ 用户与目录 ================

CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_id     BIGINT NOT NULL UNIQUE,
    github_login  TEXT NOT NULL,
    avatar_url    TEXT,
    role          TEXT NOT NULL DEFAULT 'USER'
                  CHECK (role IN ('USER', 'ADMIN')),
    create_time   TIMESTAMPTZ NOT NULL DEFAULT now(),
    update_time   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE company (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             TEXT NOT NULL,
    normalized_name  TEXT NOT NULL UNIQUE,
    create_time      TIMESTAMPTZ NOT NULL DEFAULT now(),
    update_time      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE position_category (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             TEXT NOT NULL,
    normalized_name  TEXT NOT NULL UNIQUE,
    sort_order       INT NOT NULL DEFAULT 0,
    create_time      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "position" (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             TEXT NOT NULL,
    normalized_name  TEXT NOT NULL UNIQUE,
    create_time      TIMESTAMPTZ NOT NULL DEFAULT now(),
    update_time      TIMESTAMPTZ NOT NULL DEFAULT now(),
    category_id      BIGINT NOT NULL
                     REFERENCES position_category(id)
);

CREATE TABLE tag (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             TEXT NOT NULL,
    normalized_name  TEXT NOT NULL UNIQUE,
    create_time      TIMESTAMPTZ NOT NULL DEFAULT now(),
    update_time      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ================ 面经主体 ================

CREATE TABLE interview_record (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id                BIGINT REFERENCES app_user(id),
    company_id               BIGINT REFERENCES company(id),
    position_id              BIGINT REFERENCES "position"(id),
    department               TEXT,
    original_position_name   TEXT,
    inferred_position_name   TEXT,
    note                     TEXT,
    recruit_type             TEXT
                             CHECK (recruit_type IN ('INTERN', 'CAMPUS')),
    status                   TEXT NOT NULL DEFAULT 'DRAFT'
                             CHECK (status IN ('DRAFT', 'PENDING_REVIEW', 'PUBLISHED', 'REJECTED', 'REMOVED')),
    version                  BIGINT NOT NULL DEFAULT 0,
    rejection_reason         TEXT,
    create_time              TIMESTAMPTZ NOT NULL DEFAULT now(),
    update_time              TIMESTAMPTZ NOT NULL DEFAULT now(),
    publish_time             TIMESTAMPTZ
);

CREATE INDEX interview_record_author_idx   ON interview_record (author_id);
CREATE INDEX interview_record_company_idx  ON interview_record (company_id);
CREATE INDEX interview_record_position_idx ON interview_record (position_id);

CREATE TABLE interview_source (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interview_id     BIGINT NOT NULL REFERENCES interview_record(id) ON DELETE CASCADE,
    url              TEXT NOT NULL,
    normalized_url   TEXT NOT NULL,
    create_time      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (interview_id, normalized_url)
);

CREATE INDEX interview_source_normalized_url_idx ON interview_source (normalized_url);

CREATE TABLE interview_round (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interview_id             BIGINT NOT NULL REFERENCES interview_record(id) ON DELETE CASCADE,
    round_type               TEXT NOT NULL
                             CHECK (round_type IN ('TECHNICAL', 'HR', 'UNKNOWN')),
    round_no                 INT,
    remark                   TEXT,
    interview_date           DATE,
    interview_date_precision TEXT
                             CHECK (interview_date_precision IN ('DAY', 'MONTH', 'YEAR')),
    sort_order               INT NOT NULL,
    create_time              TIMESTAMPTZ NOT NULL DEFAULT now(),
    update_time              TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (interview_id, sort_order),
    CONSTRAINT interview_round_type_no_ck CHECK (
        (round_type = 'TECHNICAL' AND round_no BETWEEN 1 AND 5)
        OR
        (round_type IN ('HR', 'UNKNOWN') AND round_no IS NULL)
    ),
    CONSTRAINT interview_round_date_ck CHECK (
        (interview_date IS NULL AND interview_date_precision IS NULL)
        OR
        (interview_date IS NOT NULL AND interview_date_precision IS NOT NULL)
    )
);

CREATE TABLE question (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    round_id               BIGINT NOT NULL REFERENCES interview_round(id) ON DELETE CASCADE,
    content                TEXT NOT NULL,
    sort_order             INT NOT NULL,
    question_type          TEXT NOT NULL DEFAULT 'NORMAL'
                           CHECK (question_type IN ('NORMAL', 'ALGORITHM')),
    section_label          TEXT,
    context_note           TEXT,
    algorithm_title        TEXT,
    algorithm_description  TEXT,
    algorithm_requirements TEXT,
    leetcode_number        INT,
    leetcode_url           TEXT,
    create_time            TIMESTAMPTZ NOT NULL DEFAULT now(),
    update_time            TIMESTAMPTZ NOT NULL DEFAULT now(),
    reference_url          TEXT,
    UNIQUE (round_id, sort_order)
);

CREATE TABLE follow_up (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id   BIGINT NOT NULL REFERENCES question(id) ON DELETE CASCADE,
    content       TEXT NOT NULL,
    sort_order    INT NOT NULL,
    create_time   TIMESTAMPTZ NOT NULL DEFAULT now(),
    update_time   TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (question_id, sort_order)
);

CREATE TABLE interview_tag (
    interview_id  BIGINT NOT NULL REFERENCES interview_record(id) ON DELETE CASCADE,
    tag_id        BIGINT NOT NULL REFERENCES tag(id),
    PRIMARY KEY (interview_id, tag_id)
);

CREATE INDEX interview_tag_tag_idx ON interview_tag (tag_id);

-- ================ 投稿治理 ================

CREATE TABLE interview_candidate (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interview_id      BIGINT NOT NULL REFERENCES interview_record(id) ON DELETE CASCADE,
    type              TEXT NOT NULL
                      CHECK (type IN ('COMPANY', 'POSITION', 'TAG')),
    value             TEXT NOT NULL,
    normalized_value  TEXT NOT NULL,
    sort_order        INT NOT NULL DEFAULT 0,
    create_time       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX interview_candidate_interview_idx ON interview_candidate (interview_id, type, sort_order);
CREATE UNIQUE INDEX interview_candidate_company_uk  ON interview_candidate (interview_id) WHERE type = 'COMPANY';
CREATE UNIQUE INDEX interview_candidate_position_uk ON interview_candidate (interview_id) WHERE type = 'POSITION';

CREATE TABLE submission_snapshot (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interview_id  BIGINT NOT NULL REFERENCES interview_record(id),
    payload       JSONB NOT NULL,
    create_time   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX submission_snapshot_interview_idx ON submission_snapshot (interview_id, create_time DESC);

CREATE TABLE interview_revision (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interview_id  BIGINT NOT NULL REFERENCES interview_record(id),
    editor_id     BIGINT NOT NULL REFERENCES app_user(id),
    base_version  BIGINT NOT NULL,
    payload       JSONB NOT NULL,
    create_time   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX interview_revision_interview_idx ON interview_revision (interview_id, create_time DESC);

CREATE TABLE change_request (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interview_id  BIGINT NOT NULL REFERENCES interview_record(id),
    requester_id  BIGINT NOT NULL REFERENCES app_user(id),
    reviewer_id   BIGINT REFERENCES app_user(id),
    type          TEXT NOT NULL
                  CHECK (type IN ('UPDATE', 'DELETE')),
    status        TEXT NOT NULL DEFAULT 'PENDING'
                  CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    base_version  BIGINT NOT NULL,
    request_version BIGINT NOT NULL DEFAULT 0
                  CHECK (request_version >= 0),
    payload       JSONB,
    reason        TEXT,
    create_time   TIMESTAMPTZ NOT NULL DEFAULT now(),
    update_time   TIMESTAMPTZ NOT NULL DEFAULT now(),
    review_time   TIMESTAMPTZ,
    CONSTRAINT change_request_payload_ck CHECK (type <> 'UPDATE' OR payload IS NOT NULL)
);

CREATE INDEX change_request_interview_idx ON change_request (interview_id, status, create_time DESC);
CREATE UNIQUE INDEX change_request_one_pending_uk ON change_request (interview_id) WHERE status = 'PENDING';

-- ================ 页尾祝福 ================

CREATE TABLE cheer (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT REFERENCES app_user(id),
    create_time   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX cheer_user_uk ON cheer (user_id) WHERE user_id IS NOT NULL;

-- ================ 岗位方向字典（初始五类） ================

INSERT INTO position_category (name, normalized_name, sort_order) VALUES
    ('Agent 开发', 'agent 开发', 1),
    ('AI 应用',    'ai 应用',    2),
    ('AI Infra',   'ai infra',   3),
    ('后端开发',   '后端开发',   4),
    ('其他',       '其他',       99);
